### ISSUE TITLE
can't write comment

### ISSUE THREAD

**Issue by Octoping925** [morethanmin/morethan_log#2]
![image](https://user-images.githubusercontent.com/53991994/173260525-b6bbe7d7-3485-46ec-981d-39e3fbfb653c.png)
The following error occurs when I press the 'Comment' button.

here is the error message.

Error: utterances is not installed on morethanmin/morethan_log. If you own this repo, [install the app](https://github.com/apps/utterances). Read more about this change in [the PR](https://github.com/utterance/utterances/pull/25).

**Comment by morethanmin** [comment]
It's fixed. thank you for the issue! ^0^

**Comment by Octoping925** [comment]
it works now
